name: Build and release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  export_release:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export and create release
    permissions:
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.1
      # Ensure that we get the entire project history
      with:
        fetch-depth: 0

    - name: Write tag version to version file
      shell: bash
      run: |
        echo "${GITHUB_REF#refs/tags/}" > ./version.txt

#    - name: Run pre-export script
#      run: ./pre_export.sh
#      shell: bash

    - name: Export project
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        relative_project_path: ./
        cache: true
        archive_output: true
        archive_root_folder: true

    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
